//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banking.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Banking.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap en {
            get {
                object obj = ResourceManager.GetObject("en", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap en1 {
            get {
                object obj = ResourceManager.GetObject("en1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UAH.
        /// </summary>
        internal static string MoneySymbol {
            get {
                return ResourceManager.GetString("MoneySymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank file not found..
        /// </summary>
        internal static string MsgBankNotFound {
            get {
                return ResourceManager.GetString("MsgBankNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card not found in bank..
        /// </summary>
        internal static string MsgCardNotFound {
            get {
                return ResourceManager.GetString("MsgCardNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter card data first..
        /// </summary>
        internal static string MsgCardNull {
            get {
                return ResourceManager.GetString("MsgCardNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The card number must contain 16 digits..
        /// </summary>
        internal static string MsgCardNumShort {
            get {
                return ResourceManager.GetString("MsgCardNumShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commission:.
        /// </summary>
        internal static string MsgCommission {
            get {
                return ResourceManager.GetString("MsgCommission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter deposit sum..
        /// </summary>
        internal static string MsgDepositEmpty {
            get {
                return ResourceManager.GetString("MsgDepositEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter PIN code..
        /// </summary>
        internal static string MsgEnterPIN {
            get {
                return ResourceManager.GetString("MsgEnterPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in all fields..
        /// </summary>
        internal static string MsgFillAll {
            get {
                return ResourceManager.GetString("MsgFillAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number entered. Please enter only numbers..
        /// </summary>
        internal static string MsgIncorrectNumber {
            get {
                return ResourceManager.GetString("MsgIncorrectNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are not enough funds in the account. With the commission you need .
        /// </summary>
        internal static string MsgNotEnough {
            get {
                return ResourceManager.GetString("MsgNotEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt saved to:  .
        /// </summary>
        internal static string MsgReceiptSaved {
            get {
                return ResourceManager.GetString("MsgReceiptSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wish to save receipt in file?.
        /// </summary>
        internal static string MsgSaveReceipt {
            get {
                return ResourceManager.GetString("MsgSaveReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving a receipt.
        /// </summary>
        internal static string MsgSaveReceiptCaption {
            get {
                return ResourceManager.GetString("MsgSaveReceiptCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succesfully deposited .
        /// </summary>
        internal static string MsgSuccesfullDeposit {
            get {
                return ResourceManager.GetString("MsgSuccesfullDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succesfully withdrew .
        /// </summary>
        internal static string MsgSuccesfullWithdrawal {
            get {
                return ResourceManager.GetString("MsgSuccesfullWithdrawal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum must be greater than 0..
        /// </summary>
        internal static string MsgSum {
            get {
                return ResourceManager.GetString("MsgSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total withdrawn: .
        /// </summary>
        internal static string MsgTotal {
            get {
                return ResourceManager.GetString("MsgTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter withdraw sum.
        /// </summary>
        internal static string MsgWithdrawSum {
            get {
                return ResourceManager.GetString("MsgWithdrawSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong CVV code..
        /// </summary>
        internal static string MsgWrongCVV {
            get {
                return ResourceManager.GetString("MsgWrongCVV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card is not found or input is incorrect..
        /// </summary>
        internal static string MsgWrongInput {
            get {
                return ResourceManager.GetString("MsgWrongInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong PIN code..
        /// </summary>
        internal static string MsgWrongPIN {
            get {
                return ResourceManager.GetString("MsgWrongPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ua {
            get {
                object obj = ResourceManager.GetObject("ua", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ua1 {
            get {
                object obj = ResourceManager.GetObject("ua1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
